# Generated by Django 5.0 on 2024-01-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
